# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97bb707beeaec702df9fd63db1f5e9df052ea0c033fa06d26b468c3106e9fb84232519bdb62c219f69a24a78691b0603d41625bc52b2c0eb8d8fb9e3bd11522f

test:
  secret_key_base: 0083248d2d2d76235c53dc166ddde79beacffa822f831bf3c7c3ab2556c0309c88b065354f9a7727faaf4ac2c604d18ac501e7234d22e90038536c55076fec9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
